<?php
/**
 * Created by PhpStorm.
 * User: Luisito Suarez
 * Date: 13/11/2017
 * Time: 22:18
 */

namespace app\models;


use yii\base\Model;

class FilterProduct extends Model
{
    public $minPrice;
    public $maxPrice;
    public $date;
    public $actividad;



    public function rules()
    {
        return [
            [['minPrice','maxPrice'],'number'],
            ['date','string'],
        ]; // TODO: Change the autogenerated stub
    }
    
    public function attributeLabels()
    {
        return [
            'minPrice'=>'',
            'maxPrice'=>'',
            'date'=>'',
            'actividad'=>'',

        ]; // TODO: Change the autogenerated stub
    }

}